set dotenv-load
set positional-arguments

default:
    @just --list

build:
    bun run build

dev:
    bun run dev

lint: type-check
    bun run lint:fix

lint-check:
    bun run lint

fmt:
    bun run format

fmt-check:
    bun run format:check

type-check:
    bun run --bun tsc --noEmit

preview: build
    bun run preview
