set dotenv-load
set positional-arguments

rustflags := "-C target-feature=+crt-static"
rust_target := "x86_64-unknown-linux-gnu"

default:
    @just --list

build:
    SQLX_OFFLINE=true \
    RUSTFLAGS='{{ rustflags }}' \
    cargo build \
        --release \
        --target '{{ rust_target }}'

dev-watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
          just dev-run "$@"

dev-run *args:
    RUSTFLAGS='{{ rustflags }}' \
    cargo run \
        --target "{{ rust_target }}" \
        -- {{ args }} \

watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
            just run "$@"

run *args:
    SQLX_OFFLINE=true \
    RUSTFLAGS='{{ rustflags }}' \
    cargo run \
        --target '{{ rust_target }}' \
        --release \
        -- "$@" \

test *args:
    SQLX_OFFLINE=true \
    RUSTFLAGS='{{ rustflags }}' \
    cargo test \
        --workspace \
        --all-features \
        -- "$@" \

test-watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
            just test "$@"

fmt-dev: lint-fix && fmt
    rustup run nightly cargo fmt --all \

lint:
    cargo clippy \
        --workspace \
        --all-features \
        -- \

lint-fix:
    cargo clippy \
        --fix \
        --allow-dirty \
        --allow-staged \
        --workspace \
        --all-features \
        -- \

fmt:
    cargo fmt --all \

sqlx-regenerate:
    #!/usr/bin/env bash
    set -euo pipefail
    TEMP_DIR="$(mktemp -d)"
    TEMP_DB="$TEMP_DIR/zet-live.db"
    export DATABASE_URL="sqlite://$TEMP_DB"
    export SQLX_OFFLINE=""
    touch "$TEMP_DB"
    trap "rm -rf '$TEMP_DIR'" EXIT
    cargo sqlx database create
    cargo sqlx migrate run
    cargo sqlx prepare --workspace

migrations-run: _migrations-ensure-db
    sqlx migrate run \

migrations-list: _migrations-ensure-db
    sqlx migrate info \

_migrations-ensure-db:
    #!/usr/bin/env bash
    if [ -z "$DATABASE_URL" ]; then
      echo "DATABASE_URL is not set";
      exit 1;
    fi
    if echo "$DATABASE_URL" | grep -v '^sqlite[0-9]*:'; then
      exit 0;
    fi
    url="$(echo "$DATABASE_URL" | sed -re 's,^(.*:(//)?)(.*),\3,g')"
    if [ -z "$url" ]; then
      echo "Could not extract path from database URL: $DATABASE_URL";
      exit 1;
    fi
    if [ -f "$url" ]; then
      exit 0;
    fi
    echo "Database file does not exist, creating it: $url";
    mkdir -p "$(dirname "$url")"
    touch "$url"

migrations-add $name="":
    name="{{ name }}"; \
    if [ -z "$name" ]; then \
        read -p "Enter migration name: " name; \
    fi; \
    sqlx migrate add -r "$name" \
