set dotenv-load
set positional-arguments

rustflags := "-C target-feature=+crt-static"
rust_target := "x86_64-unknown-linux-gnu"

default:
    @just --list

build:
    RUSTFLAGS='{{ rustflags }}' \
    cargo build \
        --release \
        --target '{{ rust_target }}'

dev-watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
          just dev-run "$@"

dev-run *args:
    RUSTFLAGS='{{ rustflags }}' \
    cargo run \
        --target "{{ rust_target }}" \
        -- {{ args }} \

watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
            just run "$@"

run *args:
    RUSTFLAGS='{{ rustflags }}' \
    cargo run \
        --target '{{ rust_target }}' \
        --release \
        -- "$@" \

test *args:
    RUSTFLAGS='{{ rustflags }}' \
    cargo test \
        --workspace \
        --all-features \
        -- "$@" \

test-watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
            just test "$@"

fmt-dev: && fmt
    rustup run nightly cargo fmt --all \

lint:
    cargo clippy \
        --workspace \
        --all-features \
        -- \

lint-fix:
    cargo clippy \
        --fix \
        --allow-dirty \
        --allow-staged \
        --workspace \
        --all-features \
        -- \

fmt: lint-fix
    cargo fmt --all \
